### ISSUE TITLE
Instructions unclear. Does not run.

### ISSUE THREAD

**Issue by the1glorfindel** [thomasrudin-mt/minetest-tile-server#24]
I am unable to start the server, due to the limits of my setup, I am only able to get the following trailing end of the output: 
<details>

```
Oct 12, 2018 10:18:06 PM org.postgresql.Driver connect
SEVERE: Connection error: 
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:417)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:380)
        at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
        at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:67)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1634)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1168)
        at io.rudin.minetest.tileserver.DBMigration.migrate(DBMigration.java:34)
        at io.rudin.minetest.tileserver.TileServer.main(TileServer.java:44)

Exception in thread "main" org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:postgresql://127.0.0.1:5432/minetest) for user 'postgres': FATAL: password authentication failed for user "postgres"
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 28P01
Error Code : 0
Message    : FATAL: password authentication failed for user "postgres"

        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:431)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:380)
        at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
        at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:67)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1634)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1168)
        at io.rudin.minetest.tileserver.DBMigration.migrate(DBMigration.java:34)
        at io.rudin.minetest.tileserver.TileServer.main(TileServer.java:44)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:417)
        ... 7 more
glorfindel@localhost:~$
```
</details>
here is the contents of tileserver.properties:
<details>

```
#tilerenderer.initialrendering.enable=true

#log.tile.updatetimings=true
tilerenderer.updateinterval=10
#log.query.performance=true
#block.parser.smartshop.enable=false
#prometheus.enable=true
minetest.db.url=jdbc:postgresql://home/glorfindel/.minetest/worlds/Final/
minetest.db.username=MapCrawler
minetest.db.password=[redacted]
static.files.location=src/main/resources/public
```
</details>
I also tried my servers public and private urls. 

I think the problem is that I am unsure of which lines exactly I am supposed to edit.
I am hosting this on Ubuntu 16.04.4. All dependencies are installed.

So, for an example machine "server@host$" hosted at "example.com", what do I do?
I'm willing to help write a walkthrough once I get this running, it looks fantastic!

**Comment by thomasrudin** [comment]
i'll look into it. let me document some new parameters and release a new version, the current "release" has a few important features missing...

**Comment by thomasrudin** [comment]
So i got around to fixing some docs and releasing a new version:
https://github.com/thomasrudin-mt/minetest-tile-server/releases/tag/1.1

But i think your problem is somewhere else, in your tileserver.properties you wrote:
```
minetest.db.url=jdbc:postgresql://home/glorfindel/.minetest/worlds/Final/
```

This should point to your postgresql-database (i hope you have one) and be in the following format:
https://jdbc.postgresql.org/documentation/80/connect.html

**Comment by the1glorfindel** [comment]
Ah, I see... No, I do not have postgresql database, AFAIK it's just sqlite3 or whatever the minetest default is. How would I go about getting it converted?

**Comment by the1glorfindel** [comment]
Aha, thanks!
This is a dedicated server, yes. I use minetest-mapper for local worlds 😁

**Comment by thomasrudin** [comment]
Closing this, please comment if further action needed

**Comment by the1glorfindel** [comment]
alright, I've got minetest with postgresql support, and the db migrated, but I am now getting authentication errors:
`Exception in thread "main" org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:postgresql://127.0.0.1:5432/minetest) for user 'postgres': FATAL: password authentication failed for user "postgres"
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 28P01
Error Code : 0
Message    : FATAL: password authentication failed for user "postgres"
`
I have set the "minetest.db.username=" and "minetest.db.password=" to minetest and <password>, as is documented in Exterdad's post that you helpfully shared. why is it trying to authenticate as user postgres?

**Comment by thomasrudin** [comment]
No idea how that would happen. Can you post a stacktrace and a redactet tileserver.properties? And are you on the newest version (1.1)?

**Comment by the1glorfindel** [comment]
Yes, I did download the 1.1 .jar, and ran that... I'm not sure what you mean by redactet tileserver.properties? I will post the entire contents of it, hopefully you can get what you need out of it.
<details><summary>stacktrace</summary>glorfindel@localhost:~$ java -jar ./tileserver/tileserver.jar 
18:27:06.595 [main] INFO  o.f.c.internal.util.VersionPrinter - Flyway Community Edition 5.0.7 by Boxfuse
Oct 28, 2018 6:27:06 PM org.postgresql.core.v3.ConnectionFactoryImpl log
WARNING: SQLException occurred while connecting to 127.0.0.1:5432
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:417)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:380)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:67)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1634)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1168)
	at io.rudin.minetest.tileserver.DBMigration.migrate(DBMigration.java:34)
	at io.rudin.minetest.tileserver.TileServer.main(TileServer.java:46)

Oct 28, 2018 6:27:06 PM org.postgresql.Driver connect
SEVERE: Connection error: 
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:417)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:380)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:67)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1634)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1168)
	at io.rudin.minetest.tileserver.DBMigration.migrate(DBMigration.java:34)
	at io.rudin.minetest.tileserver.TileServer.main(TileServer.java:46)

Exception in thread "main" org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:postgresql://127.0.0.1:5432/minetest) for user 'postgres': FATAL: password authentication failed for user "postgres"
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 28P01
Error Code : 0
Message    : FATAL: password authentication failed for user "postgres"

	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:431)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:380)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:67)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1634)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1168)
	at io.rudin.minetest.tileserver.DBMigration.migrate(DBMigration.java:34)
	at io.rudin.minetest.tileserver.TileServer.main(TileServer.java:46)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:417)
	... 7 more
glorfindel@localhost:~$ 
</details>
<details><summary>tileserver.properties</summary>
#tilerenderer.initialrendering.enable=true

#log.tile.updatetimings=true
tilerenderer.updateinterval=10
#log.query.performance=true
#block.parser.smartshop.enable=false
#prometheus.enable=true
minetest.db.url=jdbc:postgresql://127.0.0.1:5432/minetest
minetest.db.username=minetest
minetest.db.password=Jars09Clay

static.files.location=src/main/resources/public

</details>
Many thanks for your prompt assistance in this issue.

**Comment by thomasrudin** [comment]
I think i understand the problem now: the ```tileserver.properties``` is read from the current directory (CWD), did you place the properties file in the subdirectory or the directory you are executing the command from?

In your case: placing the property file in the home-directory (~/tileserver.properties) and executing the command (```java -jar ./tileserver/tileserver.jar```) should work.

**Comment by the1glorfindel** [comment]
it now runs, yay!
I did need to edit the .properties file one last time to change the name of the database as Exterdad's tutorial ends up giving you a database named myworld, not minetest. however, that much I could figure out on my own :+1: 
so now I have one last question, how do I access it?
I have apache running already, do I need to set it up to forward the tileserver? I'm assuming based off of the description (where is says it's standalone) that I shouldn't need to do anything else... if that is the case, what is the default port?

**Comment by thomasrudin** [comment]
The default port is in the readme :smile: ...
You can access it under http://127.0.0.1:8080
There are some open issues though for "real" realtime so don't get too excited... (#32 for example) but the tiles work pretty well

**Comment by the1glorfindel** [comment]
oh, whoops, I must have missed that when I was reading through it ;)
It seems I have another issue unrelated to this program that I must fix before I can run the tileserver, so I'll close this and open a new issue if I run into anything else. 
Thanks for the help!
