### ISSUE TITLE
Investigate mapblock parse issue

### ISSUE THREAD

**Issue by thomasrudin** [thomasrudin-mt/minetest-tile-server#31]
https://pandorabox.io/map/#-2094.59375/248.625/13

Situation: furnace-sculpture (maybe inv-related)

```
tileserver_1               | 09:37:23.624 [pool-3-thread-2] ERROR i.r.m.t.job.UpdateChangedTilesJob - tile-updater
tileserver_1               | com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 15800
tileserver_1               | 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2052)
tileserver_1               | 	at com.google.common.cache.LocalCache.get(LocalCache.java:3948)
tileserver_1               | 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972)
tileserver_1               | 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
tileserver_1               | 	at io.rudin.minetest.tileserver.accessor.MapBlockAccessor.get(MapBlockAccessor.java:43)
tileserver_1               | 	at io.rudin.minetest.tileserver.MapBlockRenderer.render(MapBlockRenderer.java:75)
tileserver_1               | 	at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:308)
tileserver_1               | 	at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:227)
tileserver_1               | 	at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:227)
tileserver_1               | 	at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
tileserver_1               | 	at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:227)
tileserver_1               | 	at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:229)
tileserver_1               | 	at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:229)
tileserver_1               | 	at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:229)
tileserver_1               | 	at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:228)
tileserver_1               | 	at io.rudin.minetest.tileserver.TileRenderer.render(TileRenderer.java:132)
tileserver_1               | 	at io.rudin.minetest.tileserver.job.UpdateChangedTilesJob.run(UpdateChangedTilesJob.java:269)
tileserver_1               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
tileserver_1               | 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
tileserver_1               | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
tileserver_1               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
tileserver_1               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tileserver_1               | 	at java.base/java.lang.Thread.run(Thread.java:844)
tileserver_1               | Caused by: java.lang.ArrayIndexOutOfBoundsException: 15800
tileserver_1               | 	at io.rudin.minetest.tileserver.MapBlockParser.readU16(MapBlockParser.java:17)
tileserver_1               | 	at io.rudin.minetest.tileserver.MapBlockParser.parse(MapBlockParser.java:129)
tileserver_1               | 	at io.rudin.minetest.tileserver.MapBlockParser.parse(MapBlockParser.java:30)
tileserver_1               | 	at io.rudin.minetest.tileserver.accessor.MapBlockAccessor.load(MapBlockAccessor.java:84)
tileserver_1               | 	at io.rudin.minetest.tileserver.accessor.MapBlockAccessor.load(MapBlockAccessor.java:20)
tileserver_1               | 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
tileserver_1               | 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
tileserver_1               | 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
tileserver_1               | 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
tileserver_1               | 	... 22 common frames omitted

```

**Comment by thomasrudin** [comment]
works with increased factor but needs a proper calculation solution in long term
