### ISSUE TITLE
Logs filling with errors when user browses the web page for the tile server

### ISSUE THREAD

**Issue by Ryan-Nolan** [thomasrudin-mt/minetest-tile-server#38]
My java skills are non existent so I'm hoping someone might be able to shed some light as to why these errors are showing up.

I ran the tile server with `initialrendering` enabled until it had completed rendering the initial tiles. then I restarted the tile server with `initialrendering` disabled and when i visited the web page it flooded the console with the following messages.

i also noticed that alot of the times were missing on the webpage.... I understand that the white tiles are normal for non generated map chunks but there was actual missing images within the map.

thanks in advanced.

`09:29:05.190 [qtp427748564-39] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:241)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:229)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:229)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:228)
        at io.rudin.minetest.tileserver.TileRenderer.render(TileRenderer.java:132)
        at io.rudin.minetest.tileserver.route.TileRoute.handle(TileRoute.java:95)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.base/java.lang.Thread.run(Thread.java:844)
09:29:06.117 [qtp427748564-28] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:238)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:228)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:229)
        at io.rudin.minetest.tileserver.TileRenderer.render(TileRenderer.java:132)
        at io.rudin.minetest.tileserver.route.TileRoute.handle(TileRoute.java:95)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.base/java.lang.Thread.run(Thread.java:844)
09:29:19.827 [qtp427748564-46] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:238)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:227)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:229)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.render(TileRenderer.java:132)
        at io.rudin.minetest.tileserver.route.TileRoute.handle(TileRoute.java:95)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.base/java.lang.Thread.run(Thread.java:844)
09:29:20.169 [qtp427748564-66] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:241)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:228)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:227)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:228)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.render(TileRenderer.java:132)
        at io.rudin.minetest.tileserver.route.TileRoute.handle(TileRoute.java:95)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.base/java.lang.Thread.run(Thread.java:844)
09:29:23.133 [qtp427748564-44] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:238)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:228)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:228)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:229)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.render(TileRenderer.java:132)
        at io.rudin.minetest.tileserver.route.TileRoute.handle(TileRoute.java:95)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.base/java.lang.Thread.run(Thread.java:844)
09:29:23.151 [qtp427748564-39] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:244)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:229)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:229)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.render(TileRenderer.java:132)
        at io.rudin.minetest.tileserver.route.TileRoute.handle(TileRoute.java:95)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.base/java.lang.Thread.run(Thread.java:844)
09:29:26.095 [qtp427748564-39] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:238)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:229)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:227)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:228)
        at io.rudin.minetest.tileserver.TileRenderer.render(TileRenderer.java:132)
        at io.rudin.minetest.tileserver.route.TileRoute.handle(TileRoute.java:95)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.base/java.lang.Thread.run(Thread.java:844)
09:29:27.684 [qtp427748564-46] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:238)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:227)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:227)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:226)
        at io.rudin.minetest.tileserver.TileRenderer.render(TileRenderer.java:132)
        at io.rudin.minetest.tileserver.route.TileRoute.handle(TileRoute.java:95)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.base/java.lang.Thread.run(Thread.java:844)
09:29:28.927 [qtp427748564-44] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
09:29:29.496 [qtp427748564-76] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
09:29:31.172 [qtp427748564-72] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
09:29:31.724 [qtp427748564-21] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
09:29:34.397 [qtp427748564-40] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
09:29:34.634 [qtp427748564-75] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
09:29:34.870 [qtp427748564-26] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
09:29:35.319 [qtp427748564-46] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
09:29:35.539 [qtp427748564-84] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
09:29:36.478 [qtp427748564-41] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: null
`

**Comment by thomasrudin** [comment]
Can you provide the db- and minetest-version?
But yeah, this looks not right. I may have to add some lines to catch the error and produce some meaningful error...

**Comment by Ryan-Nolan** [comment]
minetest-version 5.0.0-dev commit 81c06de

DB: postgresSQL 10.5
OS: Ubuntu 18.04 lts

**Comment by thomasrudin** [comment]
I added some debug flags in the config.
Can you enable them and run the new version?
Maybe pipe the result of the debug-run into a file...

## Snapshot-release:
https://cloud.rudin.io/index.php/s/oIbimxHaSAZ82cT

## Sha1-sum:
`ff5b19ff2a32538acae9532d70d646d5bb762454`

## New options in `tileserver.properties`:
```properties
# full debug (very verbose)
debug.enable=true
# dumps failing mapblocks to a directory for analysis
debug.mapblock.dumpfailed=true
```

**Comment by Ryan-Nolan** [comment]
Here is the log you asked for: https://gist.github.com/Ryan-Nolan/8ce11f550aeb30e5339cbf3203b8de1e

You will notice that minus a few warnings... its runs fine right until the web server is accessed. then it goes crazy <--- technical term :D

**Comment by thomasrudin** [comment]
I'm having issues reproducing this :/ is there a way you can provide the database?

**Comment by Ryan-Nolan** [comment]
erm....   do you have a way for me to contact you privately? irc/discord?

**Comment by Ryan-Nolan** [comment]
I could provide you with readonly access to the database but for obvious reasons would need to send you the details privatly

**Comment by thomasrudin** [comment]
I mailed you btw :smile: can you make a db-copy and give me the dump or .sql file? i would feel comfortabler doing it that way...

**Comment by Ryan-Nolan** [comment]
Sorry, I rarely check on tha email address. ive replied anyway and sent you a link to the database :)

**Comment by thomasrudin** [comment]
Can you try the new release:
https://github.com/thomasrudin-mt/minetest-tile-server/releases/tag/1.1.1
I think i found the issue in the layer-config parsing and it works flawlessly for me with your map-db

**Comment by Ryan-Nolan** [comment]
Seems to be working now... although still receiving some error messages:

https://gist.github.com/Ryan-Nolan/eeb0d76c1b876a130c6c6c0137615341

**Comment by thomasrudin** [comment]
That could have been invalid cached data from the previous run, can you try erasing the cache?

**And btw:** if you have a bigger installation i urge you to switch to a postgres cache, the file-cache gets very inode heavy (check with _df -i_)

**Comment by Ryan-Nolan** [comment]
im presuming the cache is the tile folder?

**Comment by thomasrudin** [comment]
Jep, it should be called **tiles**

**Comment by Ryan-Nolan** [comment]
ok. yeah i did remove that before the last run... :/

**Comment by Ryan-Nolan** [comment]
Scratch that.... I've just removed the cache... and then setup PostgreSQL cache. and it seems to be working fine. no errors so far

on a side note... should the following warning not be an info message?
`WARN  spark.staticfiles.StaticFilesFolder - Registering external static files folder [/home/user/mapper/public/] as [/home/user/mapper/public].`

Thanks for your help btw :D

**Comment by Ryan-Nolan** [comment]
I spoke to soon, it throws the following error after placing a POI:

```
Nov 09, 2018 2:29:36 PM com.google.common.eventbus.EventBus$LoggingHandler handleException
SEVERE: Exception thrown by subscriber method onMapBlock(io.rudin.minetest.tileserver.service.EventBus$MapBlockParsedEvent) on subscriber io.rudin.minetest.tileserver.listener.PoiMapBlockListener@21325036 when dispatching event: io.rudin.minetest.tileserver.service.EventBus$MapBlockParsedEvent@4cb00d00
org.jooq.exception.DataAccessException: SQL [insert into "poi" ("name", "category", "owner", "active", "x", "y", "z", "posx", "posy", "posz", "mtime", "url") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) returning "poi"."id"]; ERROR: permission denied for sequence poi_id_seq
        at org.jooq_3.10.5.POSTGRES.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2239)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
        at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:197)
        at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:168)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125)
        at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:164)
        at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:152)
        at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:147)
        at io.rudin.minetest.tileserver.listener.PoiMapBlockListener.registerPOI(PoiMapBlockListener.java:63)
        at io.rudin.minetest.tileserver.listener.PoiMapBlockListener.onMapBlock(PoiMapBlockListener.java:91)
        at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
        at com.google.common.eventbus.EventBus.post(EventBus.java:212)
        at io.rudin.minetest.tileserver.service.impl.EventBusImpl.post(EventBusImpl.java:25)
        at io.rudin.minetest.tileserver.accessor.MapBlockAccessor.prefetchTopDownYStride(MapBlockAccessor.java:73)
        at io.rudin.minetest.tileserver.MapBlockRenderer.render(MapBlockRenderer.java:72)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:314)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:232)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:234)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:232)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:233)
        at io.rudin.minetest.tileserver.TileRenderer.renderImage(TileRenderer.java:234)
        at io.rudin.minetest.tileserver.TileRenderer.render(TileRenderer.java:136)
        at io.rudin.minetest.tileserver.job.UpdateChangedTilesJob.run(UpdateChangedTilesJob.java:269)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.postgresql.util.PSQLException: ERROR: permission denied for sequence poi_id_seq
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:94)
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:551)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
```

**Comment by thomasrudin** [comment]
The stacktrace describes your problem very well:
`Caused by: org.postgresql.util.PSQLException: ERROR: permission denied for sequence poi_id_seq`
It means the tileserver has no permissions to INSERT a row into the POI table...

I'm planning to separate the tiles, blocks and markers databases but in the meantime (until 2.0 i presume) write access is still required..

**Comment by Ryan-Nolan** [comment]
Thats the first thing. i thought but when i looked.. all the permissions. looked correct... I guess ive probably missed something.... PostgreSQL is quite new to me... Anyhow. il code this. thanks for your help
